<a href="https://colab.research.google.com/github/silviyax03/PhonePe-Transaction-Insights-Dashboard/blob/main/PhonePe_Transaction_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
remote: Enumerating objects: 17904, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 17904 (delta 19), reused 17 (delta 17), pack-reused 17855 (from 2)
Receiving objects: 100% (17904/17904), 26.13 MiB | 13.28 MiB/s, done.
Resolving deltas: 100% (8723/8723), done.
Updating files: 100% (9029/9029), done.

In [2]:
!ls pulse

data  LICENSE  README.md

In [3]:
import os
import json
import pandas as pd
import sqlite3

In [4]:
path = "/content/pulse/data/aggregated/transaction/country/india/state"

records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):
        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):
                if file.endswith(".json"):

                    with open(os.path.join(year_path, file), "r") as f:
                        data = json.load(f)

                    quarter = int(file.replace(".json", ""))

                    try:
                        transactions = data["data"]["transactionData"]

                        if transactions:
                            for item in transactions:
                                records.append({
                                    "State": state.replace("-", " ").title(),
                                    "Year": int(year),
                                    "Quarter": quarter,
                                    "Transaction_Type": item["name"],
                                    "Count": item["paymentInstruments"][0]["count"],
                                    "Amount": item["paymentInstruments"][0]["amount"]
                                })
                    except:
                        pass

df = pd.DataFrame(records)

df.head()

,State,Year,Quarter,Transaction_Type,Count,Amount
0,Andhra Pradesh,2018,3,Peer-to-peer payments,16129591,3.273863e+10
1,Andhra Pradesh,2018,3,Recharge & bill payments,7542005,1.949098e+09
2,Andhra Pradesh,2018,3,Merchant payments,1225416,6.852773e+08
3,Andhra Pradesh,2018,3,Financial Services,380324,6.079008e+07
4,Andhra Pradesh,2018,3,Others,348725,2.842487e+08

In [5]:
conn = sqlite3.connect("phonepe.db")

df.to_sql(
    "aggregated_transaction",
    conn,
    if_exists="replace",
    index=False
)

print("Data inserted successfully")

Data inserted successfully

In [6]:
path = "/content/pulse/data/aggregated/user/country/india/state"

user_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):
        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):
                if file.endswith(".json"):

                    with open(os.path.join(year_path, file), "r") as f:
                        data = json.load(f)

                    quarter = int(file.replace(".json", ""))

                    try:
                        users = data["data"]["usersByDevice"]

                        if users:
                            for user in users:
                                user_records.append({
                                    "State": state.replace("-", " ").title(),
                                    "Year": int(year),
                                    "Quarter": quarter,
                                    "Brand": user["brand"],
                                    "Count": user["count"],
                                    "Percentage": user["percentage"]
                                })

                    except:
                        pass

df_user = pd.DataFrame(user_records)

df_user.head()

            State  Year  Quarter    Brand    Count  Percentage
0  Andhra Pradesh  2018        3   Xiaomi  1385112    0.255197
1  Andhra Pradesh  2018        3  Samsung  1103186    0.203254
2  Andhra Pradesh  2018        3     Vivo   761793    0.140355
3  Andhra Pradesh  2018        3     Oppo   518120    0.095460
4  Andhra Pradesh  2018        3   Realme   379712    0.069959

In [7]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_user.to_sql(
    "aggregated_user",
    conn,
    if_exists="replace",
    index=False
)

print("aggregated_user table created successfully!")

aggregated_user table created successfully!

In [8]:
path = "/content/pulse/data/aggregated/insurance/country/india/state"

insurance_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    with open(os.path.join(year_path, file), "r") as f:
                        data = json.load(f)

                    try:
                        insurance_data = data["data"]["transactionData"]

                        if insurance_data:

                            for item in insurance_data:

                                insurance_records.append({
                                    "state": state.replace("-", " ").title(),
                                    "year": int(year),
                                    "quarter": quarter,
                                    "insurance_type": item["name"],
                                    "insurance_count": item["paymentInstruments"][0]["count"],
                                    "insurance_amount": item["paymentInstruments"][0]["amount"]
                                })

                    except Exception:
                        pass

df_insurance = pd.DataFrame(insurance_records)

df_insurance.head()

,state,year,quarter,insurance_type,insurance_count,insurance_amount
0,Andhra Pradesh,2021,3,Insurance,23075,19914338.0
1,Andhra Pradesh,2021,1,Insurance,22105,12749874.0
2,Andhra Pradesh,2021,2,Insurance,33205,22730687.0
3,Andhra Pradesh,2021,4,Insurance,25423,31610335.0
4,Andhra Pradesh,2020,3,Insurance,49812,12426481.0

In [9]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_insurance.to_sql(
    "aggregated_insurance",
    conn,
    if_exists="replace",
    index=False
)

print("aggregated_insurance table created successfully")

aggregated_insurance table created successfully

In [10]:
path = "/content/pulse/data/map/user/hover/country/india/state"

map_user_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        districts = data["data"]["hoverData"]

                        for district, values in districts.items():
                            map_user_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "district": district,
                                "registered_users": values.get("registeredUsers", 0),
                                "app_opens": values.get("appOpens", 0)
                            })

                    except Exception:
                        pass

df_map_user = pd.DataFrame(map_user_records)

df_map_user.head()

,state,year,quarter,district,registered_users,app_opens
0,Andhra Pradesh,2018,3,east godavari district,558982,0
1,Andhra Pradesh,2018,3,srikakulam district,228456,0
2,Andhra Pradesh,2018,3,visakhapatnam district,769096,0
3,Andhra Pradesh,2018,3,prakasam district,314899,0
4,Andhra Pradesh,2018,3,anantapur district,405855,0

In [11]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_map_user.to_sql(
    "map_user",
    conn,
    if_exists="replace",
    index=False
)

print("map_user table created successfully")

map_user table created successfully

In [12]:
path = "/content/pulse/data/map/transaction/hover/country/india/state"

map_transaction_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        districts = data["data"]["hoverDataList"]

                        for item in districts:
                            map_transaction_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "district": item.get("name"),
                                "transaction_count": item.get("metric", [])[0].get("count", 0),
                                "transaction_amount": item.get("metric", [])[0].get("amount", 0)
                            })

                    except Exception:
                        pass

df_map_transaction = pd.DataFrame(map_transaction_records)

df_map_transaction.head()

,state,year,quarter,district,transaction_count,transaction_amount
0,Andhra Pradesh,2018,3,east godavari district,3226907,3.551247e+09
1,Andhra Pradesh,2018,3,srikakulam district,1073883,1.318322e+09
2,Andhra Pradesh,2018,3,spsr nellore district,1308890,2.215939e+09
3,Andhra Pradesh,2018,3,vizianagaram district,970132,1.163546e+09
4,Andhra Pradesh,2018,3,visakhapatnam district,3394576,4.821892e+09

In [13]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_map_transaction.to_sql(
    "map_transaction",
    conn,
    if_exists="replace",
    index=False
)

print("map_transaction table created successfully")

map_transaction table created successfully

In [14]:
path = "/content/pulse/data/map/insurance/hover/country/india/state"

map_insurance_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        districts = data["data"]["hoverDataList"]

                        for item in districts:
                            map_insurance_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "district": item.get("name"),
                                "insurance_count": item.get("metric", [])[0].get("count", 0),
                                "insurance_amount": item.get("metric", [])[0].get("amount", 0)
                            })

                    except Exception:
                        pass

df_map_insurance = pd.DataFrame(map_insurance_records)

df_map_insurance.head()

,state,year,quarter,district,insurance_count,insurance_amount
0,Andhra Pradesh,2021,3,east godavari district,2248,2073825.0
1,Andhra Pradesh,2021,3,srikakulam district,798,803258.0
2,Andhra Pradesh,2021,3,spsr nellore district,1486,1161025.0
3,Andhra Pradesh,2021,3,vizianagaram district,736,628946.0
4,Andhra Pradesh,2021,3,visakhapatnam district,4044,3191769.0

In [15]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_map_insurance.to_sql(
    "map_insurance",
    conn,
    if_exists="replace",
    index=False
)

print("map_insurance table created successfully")

map_insurance table created successfully

In [16]:
path = "/content/pulse/data/top/user/country/india/state"

top_user_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        # District-wise top users
                        districts = data["data"]["districts"]

                        for item in districts:
                            top_user_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "district",
                                "entity_name": item.get("name"),
                                "registered_users": item.get("registeredUsers", 0)
                            })

                        # Pincode-wise top users
                        pincodes = data["data"]["pincodes"]

                        for item in pincodes:
                            top_user_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "pincode",
                                "entity_name": item.get("name"),
                                "registered_users": item.get("registeredUsers", 0)
                            })

                    except Exception:
                        pass

df_top_user = pd.DataFrame(top_user_records)

df_top_user.head()

            state  year  quarter entity_type    entity_name  registered_users
0  Andhra Pradesh  2018        3    district  visakhapatnam            769096
1  Andhra Pradesh  2018        3    district  east godavari            558982
2  Andhra Pradesh  2018        3    district        krishna            537086
3  Andhra Pradesh  2018        3    district         guntur            518931
4  Andhra Pradesh  2018        3    district       chittoor            515727

In [17]:
import sqlite3

conn = sqlite3.connect("phonepe.db")

df_top_user.to_sql(
    "top_user",
    conn,
    if_exists="replace",
    index=False
)

print("top_user table created successfully")

top_user table created successfully

In [18]:
path = "/content/pulse/data/top/transaction/country/india/state"

top_transaction_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        # Top districts
                        districts = data["data"]["districts"]

                        for item in districts:
                            top_transaction_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "district",
                                "entity_name": item.get("entityName"),
                                "transaction_count": item.get("metric", {}).get("count", 0),
                                "transaction_amount": item.get("metric", {}).get("amount", 0)
                            })

                        # Top pincodes
                        pincodes = data["data"]["pincodes"]

                        for item in pincodes:
                            top_transaction_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "pincode",
                                "entity_name": item.get("entityName"),
                                "transaction_count": item.get("metric", {}).get("count", 0),
                                "transaction_amount": item.get("metric", {}).get("amount", 0)
                            })

                    except Exception:
                        pass

df_top_transaction = pd.DataFrame(top_transaction_records)

df_top_transaction.head()

,state,year,quarter,entity_type,entity_name,transaction_count,transaction_amount
0,Andhra Pradesh,2018,3,district,visakhapatnam,3394576,4.821892e+09
1,Andhra Pradesh,2018,3,district,east godavari,3226907,3.551247e+09
2,Andhra Pradesh,2018,3,district,kurnool,2921189,2.908389e+09
3,Andhra Pradesh,2018,3,district,krishna,2396934,3.754203e+09
4,Andhra Pradesh,2018,3,district,chittoor,2297429,3.283518e+09

In [19]:
conn = sqlite3.connect("phonepe.db")

df_top_transaction.to_sql(
    "top_transaction",
    conn,
    if_exists="replace",
    index=False
)

print("top_transaction table created successfully")

top_transaction table created successfully

In [20]:
path = "/content/pulse/data/top/insurance/country/india/state"

top_insurance_records = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    if os.path.isdir(state_path):

        for year in os.listdir(state_path):
            year_path = os.path.join(state_path, year)

            for file in os.listdir(year_path):

                if file.endswith(".json"):

                    quarter = int(file.replace(".json", ""))

                    file_path = os.path.join(year_path, file)

                    with open(file_path, "r") as f:
                        data = json.load(f)

                    try:
                        # Top districts
                        districts = data["data"]["districts"]

                        for item in districts:
                            top_insurance_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "district",
                                "entity_name": item.get("entityName"),
                                "insurance_count": item.get("metric", {}).get("count", 0),
                                "insurance_amount": item.get("metric", {}).get("amount", 0)
                            })

                        # Top pincodes
                        pincodes = data["data"]["pincodes"]

                        for item in pincodes:
                            top_insurance_records.append({
                                "state": state.replace("-", " ").title(),
                                "year": int(year),
                                "quarter": quarter,
                                "entity_type": "pincode",
                                "entity_name": item.get("entityName"),
                                "insurance_count": item.get("metric", {}).get("count", 0),
                                "insurance_amount": item.get("metric", {}).get("amount", 0)
                            })

                    except Exception:
                        pass

df_top_insurance = pd.DataFrame(top_insurance_records)

df_top_insurance.head()

,state,year,quarter,entity_type,entity_name,insurance_count,insurance_amount
0,Andhra Pradesh,2021,3,district,visakhapatnam,4044,3191769.0
1,Andhra Pradesh,2021,3,district,krishna,3258,2722279.0
2,Andhra Pradesh,2021,3,district,guntur,2519,2102143.0
3,Andhra Pradesh,2021,3,district,east godavari,2248,2073825.0
4,Andhra Pradesh,2021,3,district,chittoor,1991,1995617.0

In [21]:
conn = sqlite3.connect("phonepe.db")

df_top_insurance.to_sql(
    "top_insurance",
    conn,
    if_exists="replace",
    index=False
)

print("top_insurance table created successfully")

top_insurance table created successfully

In [22]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("phonepe.db")

In [23]:
#1.Decoding Transaction Dynamics on PhonePe
#aggregated_transaction
#Finding: Transaction activity is highly uneven across states and shows clear seasonal/quarterly variation. Some states consistently dominate digital payments.

In [24]:
#1.State-wise transaction volume
#Finding: A small number of states contribute most of the transaction value.
#Business Value: Helps identify high-revenue markets for expansion.

query = """
SELECT state, SUM(Amount) AS total_amount
FROM aggregated_transaction
GROUP BY state;
"""
result = pd.read_sql_query(query, conn)
#result
df=pd.DataFrame(result)
df

                                 State  total_amount
0            Andaman & Nicobar Islands  7.066745e+10
1                       Andhra Pradesh  3.466908e+13
2                    Arunachal Pradesh  2.744350e+11
3                                Assam  3.460792e+12
4                                Bihar  1.790135e+13
5                           Chandigarh  2.929066e+11
6                         Chhattisgarh  4.890472e+12
7   Dadra & Nagar Haveli & Daman & Diu  2.017199e+11
8                                Delhi  1.163752e+13
9                                  Goa  5.110212e+11
10                             Gujarat  1.019291e+13
11                             Haryana  9.645037e+12
12                    Himachal Pradesh  6.875374e+11
13                     Jammu & Kashmir  1.184683e+12
14                           Jharkhand  5.906646e+12
15                           Karnataka  4.067872e+13
16                              Kerala  3.076269e+12
17                              Ladakh  8.899462e+10
18                         Lakshadweep  1.609321e+09
19                      Madhya Pradesh  1.912528e+13
20                         Maharashtra  4.037420e+13
21                             Manipur  1.862656e+11
22                           Meghalaya  1.625439e+11
23                             Mizoram  4.610210e+10
24                            Nagaland  1.303586e+11
25                              Odisha  1.226398e+13
26                          Puducherry  2.373171e+11
27                              Punjab  2.983078e+12
28                           Rajasthan  2.634324e+13
29                              Sikkim  1.189454e+11
30                          Tamil Nadu  1.193622e+13
31                           Telangana  4.165596e+13
32                             Tripura  2.005834e+11
33                       Uttar Pradesh  2.688521e+13
34                         Uttarakhand  1.916489e+12
35                         West Bengal  1.558416e+13

In [25]:
#2. Quarterly trend analysis
#Finding: Transactions increase in specific quarters (festival/salary periods).
#Business Value: Helps plan campaigns during peak seasons.

query = """
SELECT year, quarter, SUM(amount) AS total_amount
FROM aggregated_transaction
GROUP BY year, quarter
ORDER BY year, quarter;
"""
result = pd.read_sql_query(query, conn)

df1=pd.DataFrame(result)
df1

    Year  Quarter  total_amount
0   2018        1  1.718334e+11
1   2018        2  3.043742e+11
2   2018        3  4.751015e+11
3   2018        4  6.717362e+11
4   2019        1  9.900214e+11
5   2019        2  1.354214e+12
6   2019        3  1.672559e+12
7   2019        4  2.259894e+12
8   2020        1  2.697112e+12
9   2020        2  2.646145e+12
10  2020        3  3.902053e+12
11  2020        4  5.395851e+12
12  2021        1  6.284243e+12
13  2021        2  7.476466e+12
14  2021        3  9.216696e+12
15  2021        4  1.162129e+13
16  2022        1  1.323963e+13
17  2022        2  1.550419e+13
18  2022        3  1.660763e+13
19  2022        4  1.891489e+13
20  2023        1  2.051396e+13
21  2023        2  2.291849e+13
22  2023        3  2.401213e+13
23  2023        4  2.704723e+13
24  2024        1  2.945843e+13
25  2024        2  3.182035e+13
26  2024        3  3.234697e+13
27  2024        4  3.599880e+13

In [26]:
#5. Year-wise growth
#Finding: Strong year-on-year growth in digital payments.
#Business Value: Shows overall platform expansion success.
query = """SELECT Year, SUM(Amount) AS total_amount
FROM aggregated_transaction
GROUP BY year;"""
result = pd.read_sql_query(query, conn)

df2=pd.DataFrame(result)
df2

   Year  total_amount
0  2018  1.623045e+12
1  2019  6.276688e+12
2  2020  1.464116e+13
3  2021  3.459870e+13
4  2022  6.426633e+13
5  2023  9.449181e+13
6  2024  1.296246e+14

In [27]:
query = """
SELECT state, SUM(insurance_count) AS total_count
FROM aggregated_insurance
GROUP BY state ORDER BY total_count DESC;
"""
result = pd.read_sql_query(query, conn)

df3=pd.DataFrame(result)
df3

                                 state  total_count
0                            Karnataka      1957404
1                          Maharashtra      1815539
2                           Tamil Nadu      1215269
3                        Uttar Pradesh      1139153
4                            Telangana       894342
5                          West Bengal       839715
6                               Kerala       824235
7                       Andhra Pradesh       697769
8                                Delhi       652514
9                            Rajasthan       639684
10                             Haryana       573738
11                             Gujarat       562595
12                               Bihar       536592
13                      Madhya Pradesh       487180
14                              Odisha       318769
15                               Assam       262818
16                           Jharkhand       260827
17                        Chhattisgarh       189517
18                              Punjab       180011
19                         Uttarakhand       124374
20                     Jammu & Kashmir        78375
21                    Himachal Pradesh        61790
22                                 Goa        59872
23                          Puducherry        27940
24                             Tripura        25192
25                          Chandigarh        22079
26  Dadra & Nagar Haveli & Daman & Diu        13792
27           Andaman & Nicobar Islands        12997
28                           Meghalaya        10461
29                   Arunachal Pradesh        10214
30                              Sikkim         4896
31                            Nagaland         4745
32                             Manipur         3731
33                             Mizoram         3724
34                              Ladakh         3338
35                         Lakshadweep          496

In [28]:
query = """
SELECT state, SUM(transaction_amount) AS total_amount
FROM top_transaction
GROUP BY state ORDER BY total_amount desc"""
result = pd.read_sql_query(query, conn)

df4=pd.DataFrame(result)
df4

                                 state  total_amount
0                            Telangana  4.334496e+13
1                            Karnataka  3.749980e+13
2                          Maharashtra  3.475058e+13
3                       Andhra Pradesh  3.128970e+13
4                            Rajasthan  2.235769e+13
5                                Delhi  1.581776e+13
6                       Madhya Pradesh  1.489464e+13
7                        Uttar Pradesh  1.485985e+13
8                          West Bengal  1.385772e+13
9                                Bihar  1.229505e+13
10                              Odisha  1.027377e+13
11                             Gujarat  9.867158e+12
12                          Tamil Nadu  9.719374e+12
13                             Haryana  9.697781e+12
14                           Jharkhand  5.701249e+12
15                        Chhattisgarh  4.905083e+12
16                              Punjab  3.158411e+12
17                              Kerala  3.100456e+12
18                               Assam  2.896607e+12
19                         Uttarakhand  2.697088e+12
20                     Jammu & Kashmir  1.236876e+12
21                    Himachal Pradesh  9.029089e+11
22                                 Goa  7.741372e+11
23                          Chandigarh  5.361889e+11
24                          Puducherry  4.054224e+11
25  Dadra & Nagar Haveli & Daman & Diu  4.033996e+11
26                   Arunachal Pradesh  3.719825e+11
27                             Manipur  3.030874e+11
28                             Tripura  2.728117e+11
29                           Meghalaya  2.562551e+11
30                            Nagaland  2.206469e+11
31                              Sikkim  2.151121e+11
32                              Ladakh  1.716392e+11
33           Andaman & Nicobar Islands  1.337189e+11
34                             Mizoram  7.455613e+10
35                         Lakshadweep  3.218642e+09

In [29]:
#Year trend
#Finding: Continuous growth in user base.
#Business Value: Confirms platform scaling success.
query = """SELECT year, SUM(registered_users) AS total_users
FROM map_user GROUP BY year;"""
result = pd.read_sql_query(query, conn)

df4=pd.DataFrame(result)
df4

   year  total_users
0  2018    292797872
1  2019    602811578
2  2020    922009385
3  2021   1269755730
4  2022   1614644108
5  2023   1927042597
6  2024   2235135588

In [30]:
query = """SELECT state, SUM(count) AS total_users
FROM aggregated_user GROUP BY State order by total_users desc"""
result = pd.read_sql_query(query, conn)
df7=pd.DataFrame(result)
df7

                                 State  total_users
0                          Maharashtra    452075011
1                        Uttar Pradesh    355969633
2                            Karnataka    291372780
3                       Andhra Pradesh    225414835
4                            Rajasthan    215645588
5                            Telangana    211907753
6                          West Bengal    206129775
7                           Tamil Nadu    193665028
8                              Gujarat    180731308
9                       Madhya Pradesh    180662446
10                               Bihar    167266170
11                               Delhi    133679039
12                             Haryana    121872882
13                              Odisha    114580607
14                              Kerala     76662576
15                              Punjab     66429452
16                           Jharkhand     64541996
17                        Chhattisgarh     54136914
18                               Assam     39481411
19                         Uttarakhand     34161100
20                    Himachal Pradesh     19411836
21                     Jammu & Kashmir     14122428
22                                 Goa      6844584
23                          Chandigarh      5335570
24                             Tripura      5299920
25                          Puducherry      4052989
26  Dadra & Nagar Haveli & Daman & Diu      3896519
27                             Manipur      3479129
28                   Arunachal Pradesh      2805570
29                            Nagaland      2218657
30                           Meghalaya      2155644
31                              Sikkim      1870915
32                             Mizoram       929959
33                              Ladakh       840584
34           Andaman & Nicobar Islands       623446
35                         Lakshadweep        51138

In [31]:
#Finding: Strong regional imbalance in user base.
#Business Value: Target onboarding in low-user states.
query = """SELECT state, SUM(registered_users) AS total_users
FROM map_user GROUP BY state order by total_users desc;"""
result = pd.read_sql_query(query, conn)
df8=pd.DataFrame(result)
df8

                                 state  total_users
0                          Maharashtra   1140138243
1                        Uttar Pradesh    942334146
2                            Karnataka    733674236
3                       Andhra Pradesh    556747126
4                            Rajasthan    555774493
5                          West Bengal    524964358
6                            Telangana    524620520
7                           Tamil Nadu    506486772
8                       Madhya Pradesh    470663624
9                              Gujarat    459154666
10                               Bihar    446115282
11                               Delhi    324608095
12                             Haryana    306022101
13                              Odisha    290005345
14                              Kerala    204758075
15                              Punjab    171432251
16                           Jharkhand    169283936
17                        Chhattisgarh    142291017
18                               Assam    111842317
19                         Uttarakhand     86930925
20                    Himachal Pradesh     49799825
21                     Jammu & Kashmir     40162530
22                                 Goa     17437286
23                             Tripura     13862627
24                          Chandigarh     12855589
25                          Puducherry     10407148
26  Dadra & Nagar Haveli & Daman & Diu     10080195
27                             Manipur      9389131
28                   Arunachal Pradesh      8046446
29                            Nagaland      6297675
30                           Meghalaya      6185282
31                              Sikkim      4868004
32                             Mizoram      2701061
33                              Ladakh      2271369
34           Andaman & Nicobar Islands      1842465
35                         Lakshadweep       142697

In [32]:
#Finding: Insurance adoption is increasing yearly.
#Business Value: Shows strong growth opportunity.
query = """SELECT year, SUM(insurance_amount) AS total_amount
FROM aggregated_insurance GROUP BY year;"""
result = pd.read_sql_query(query, conn)
df9=pd.DataFrame(result)
df9

   year  total_amount
0  2020  2.942072e+08
1  2021  1.499170e+09
2  2022  4.238843e+09
3  2023  6.056606e+09
4  2024  7.926752e+09

In [57]:
#st.subheader("Geographic Insights")
    # Aggregate transaction amount by state
import plotly.express as px
query = """SELECT State,SUM(Amount) AS Total_Amount
    FROM aggregated_transaction GROUP BY State"""

df5 = pd.read_sql_query(query, conn)

    # State name corrections (if needed)
df5["State"] = df5["State"].replace({"Andaman & Nicobar Islands": "Andaman and Nicobar Islands",
        "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
    })

    # India GeoJSON
geojson_url = "https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson"

fig = px.choropleth(df5,geojson=geojson_url,featureidkey="properties.ST_NM",locations="State",
        color="Total_Amount",color_continuous_scale="Reds",title="State-wise Transaction Amount")

fig.update_geos(fitbounds="locations",visible=False)

fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})

#st.plotly_chart(fig, use_container_width=True)
fig.show()

In [37]:
#!pip install streamlit pyngrok
!pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 23.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 58.1 MB/s eta 0:00:00

In [43]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

conn = sqlite3.connect("phonepe.db")

st.title("PhonePe Transaction Insights Dashboard")

menu = st.sidebar.selectbox("Select Analysis", [
    "Home",
    "Transactions Analysis",
    "User Analysis",
    "Insurance Analysis",
    "Geographic Insights",
    "Insights & Findings"
])
# ---------------- HOME ----------------
if menu == "Home":
    st.markdown("""
    ### 📌 Overview
    This dashboard analyzes **PhonePe Pulse data** to understand digital payment trends across India.
    It provides insights into transactions, users, insurance, and geographic performance.
    """)

    # ---------------- KPI METRICS ----------------
    st.subheader("📌 Key Metrics")

    col1, col2, col3, col4 = st.columns(4)

    # Total Transactions
    txn_amount = pd.read_sql_query("SELECT SUM(Amount) AS total FROM aggregated_transaction", conn )["total"][0]
    # Total Users
    users = pd.read_sql_query("SELECT SUM(registered_users) AS total FROM map_user", conn)["total"][0]
    # Insurance Amount
    ins = pd.read_sql_query("SELECT SUM(insurance_amount) AS total FROM aggregated_insurance", conn)["total"][0]
    # Transaction Count
    txn_count = pd.read_sql_query("SELECT SUM(Count) AS total FROM aggregated_transaction", conn)["total"][0]

    col1.metric("💰 Total Transactions", f"{txn_amount:,.0f}")
    col2.metric("👥 Total Users", f"{users:,.0f}")
    col3.metric("🛡️ Insurance Amount", f"{ins:,.0f}")
    col4.metric("📊 Transaction Count", f"{txn_count:,.0f}")

    st.markdown("---")

    # ---------------- OBJECTIVE ----------------
    st.subheader("🎯 Objectives")
    st.markdown("""
    - Analyze transaction growth over years
    - Study user adoption of digital payments
    - Understand insurance usage trends
    - Visualize state-wise performance
    - Identify top performing regions in India
    """)

    st.markdown("---")

    # ---------------- FEATURES ----------------
    st.subheader("⚙️ Dashboard Features")
    st.markdown("""
    ✔ Transaction Analysis (Year, Quarter, State)
    ✔ User Analysis (Brands, Registered Users)
    ✔ Insurance Analysis (Amount & Count)
    ✔ Geographic Insights (India Map Visualization)
    ✔ Top Performers (States & Districts)
    """)

    st.markdown("---")

    # ---------------- FOOTER ----------------
    st.success("📌 Developed for PhonePe Pulse Data Visualization Mini Project")
# ---------------- TRANSACTIONS ----------------
elif menu == "Transactions Analysis":

# ---------------- TRANSACTIONS1 ----------------
    query = """SELECT Year, SUM(Amount) AS total_amount
    FROM aggregated_transaction GROUP BY Year ORDER BY Year;"""

    df2 = pd.read_sql_query(query, conn)

    st.subheader("Year-wise Growth in Transaction Amount")

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.lineplot(data=df2,x="Year",y="total_amount",marker="o",linewidth=3,color="green",ax=ax)
    ax.set_title("Year-wise Growth in Digital Transactions")
    ax.set_xlabel("Year")
    ax.set_ylabel("Total Transaction Amount (₹)")
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df2)

# ---------------- TRANSACTIONS2 ----------------
    df = pd.read_sql_query("SELECT * FROM aggregated_transaction",conn)

    st.subheader("Top 10 States by Transaction Amount")
    top = (df.groupby("State")["Amount"].sum().sort_values(ascending=False).head(10))
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(x=top.values,y=top.index,palette="Blues_r",ax=ax)
    ax.set_title("Top 10 States by Transaction Amount")
    ax.set_xlabel("Total Transaction Amount")
    ax.set_ylabel("State")
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df)
  # ---------------- TRANSACTIONS3 ----------------
    df_txn = pd.read_sql_query("SELECT * FROM aggregated_transaction", conn)
    st.subheader("Quarterly Transaction Trend")
    trend = df_txn.groupby(["Year","Quarter"])["Amount"].sum().reset_index()
    fig, ax =plt.subplots(figsize=(10,5))
    sns.lineplot(data=trend, x="Quarter", y="Amount", hue="Year")
    plt.title("Quarterly Transaction Trend")
    st.pyplot(fig)
    st.dataframe(trend)

  # ---------------- TRANSACTIONS4 ----------------
    query = """SELECT state, SUM(transaction_amount) AS total_amount FROM top_transaction
    GROUP BY state ORDER BY total_amount desc"""
    df1 = pd.read_sql_query(query, conn)

    st.subheader("State-wise Total Transaction Amount")
    fig, ax =plt.subplots(figsize=(14, 6))
    sns.barplot(data=df1,x='state',y='total_amount',hue='state',palette='viridis',legend=False,ax=ax)
    plt.title('State-wise Total Transaction Amount', fontsize=16)
    plt.xlabel('State', fontsize=12)
    plt.ylabel('Total Transaction Amount', fontsize=12)
    plt.xticks(rotation=90)  # Rotate state names for better readability
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df1)
  # ---------------- USERS ----------------
elif menu == "User Analysis":
  # ---------------- USERS1 ----------------
    query = """SELECT state, SUM(count) AS total_users FROM aggregated_user
    GROUP BY State order by total_users desc"""
    df7 = pd.read_sql_query(query, conn)
    st.subheader("Total Users by State")
    fig, ax =plt.subplots(figsize=(12,6))
    sns.barplot(data=df7,x='State',y='total_users',hue="total_users",palette='viridis')
    plt.title('Total Users by State')
    plt.xlabel('State')
    plt.ylabel('Total Users')
    plt.xticks(rotation=90)  # Rotate state names for better readability
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df7)
  # ---------------- USERS2 ----------------
    df = pd.read_sql_query("SELECT * FROM aggregated_user", conn)
    st.subheader("Device Usage Distribution")
    device = df.groupby("Brand")["Count"].sum().sort_values(ascending=False)
    st.write("Top Device Brands")
    fig, ax = plt.subplots(figsize=(4,4))
    ax.pie(device.head(6),labels=device.head(6).index,autopct="%1.1f%%")
    ax.set_title("Device Usage Distribution")
    st.pyplot(fig)
    st.dataframe(device)
  # ---------------- USERS3 ----------------
    query = """SELECT year, SUM(registered_users) AS total_users
    FROM map_user GROUP BY year;"""
    df4 = pd.read_sql_query(query, conn)
    st.subheader("Year-wise Registered Users")
    fig,ax=plt.subplots(figsize=(10, 5))
    sns.lineplot(data=df4,x='year',y='total_users',marker='o',linewidth=2.5,ax=ax)
    plt.title('Year-wise Registered Users')
    plt.xlabel('Year')
    plt.ylabel('Total Registered Users')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df4)
  # ---------------- USERS4 ----------------
    query = """SELECT state, SUM(registered_users) AS total_users
    FROM map_user GROUP BY state order by total_users desc;"""
    df8 = pd.read_sql_query(query, conn)
    st.subheader("Registered Users by State")
    fig, ax =plt.subplots(figsize=(12,6))
    sns.barplot(data=df8,x='state',y='total_users',hue='total_users',palette='crest')
    plt.title('Registered Users by State')
    plt.ylabel('Registered Users')
    plt.xlabel('State')
    plt.xticks(rotation=90)
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df8)
# ---------------- INSURANCE ----------------
elif menu == "Insurance Analysis":

 # ---------------- Insurance 1 ----------------
    query = """SELECT state,SUM(insurance_count) AS total_count FROM aggregated_insurance
    GROUP BY state ORDER BY total_count DESC;"""
    # Extract data from database
    df = pd.read_sql_query(query, conn)
    # Display data
    st.subheader("Insurance Count by State")
    # Line Plot
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.lineplot(data=df,x="state",y="total_count",marker="o",linewidth=2,color="blue",ax=ax)
    ax.set_title("State-wise Insurance Count")
    ax.set_xlabel("State")
    ax.set_ylabel("Total Insurance Count")
    plt.xticks(rotation=90)
    plt.tight_layout()
    st.pyplot(fig)
    st.dataframe(df)
#--------- Insurance 2 ----------------
    st.subheader("Insurance Amount Analysis")
    df_amount = pd.read_sql_query("SELECT * FROM aggregated_insurance",conn)
    top = (df_amount.groupby("state")["insurance_amount"].sum().sort_values(ascending=False).head(10))
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(x=top.values,y=top.index,palette="viridis",ax=ax)
    ax.set_title("Top 10 States by Insurance Amount")
    ax.set_xlabel("Insurance Amount")
    ax.set_ylabel("State")
    st.pyplot(fig)
    st.dataframe(df_amount)
#--------- Insurance 3 ----------------
    query = """SELECT year, SUM(insurance_amount) AS total_amount
    FROM aggregated_insurance GROUP BY year;"""
    df9 = pd.read_sql_query(query, conn)
    st.subheader("Total Insurance Amount by Year")
    fig, ax = plt.subplots(figsize=(6,4))
    sns.lineplot(data=df9,x='year',y='total_amount',marker='o',linewidth=3,color='royalblue')
    plt.title('Total Insurance Amount by Year', fontsize=14)
    plt.xlabel('Year')
    plt.ylabel('Insurance Amount')
    plt.grid(True, linestyle='--', alpha=0.6)
    st.pyplot(fig)
    st.dataframe(df9)
# ---------------- Geographic Insights ----------------
elif menu == "Geographic Insights":
    st.subheader("Geographic Insights")
    # Aggregate transaction amount by state
    query = """SELECT State,SUM(Amount) AS Total_Amount
    FROM aggregated_transaction GROUP BY State"""
    df6 = pd.read_sql_query(query, conn)
    # State name corrections (if needed)
    df6["State"] = df6["State"].replace({"Andaman & Nicobar Islands": "Andaman and Nicobar Islands",
        "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
    })
    st.dataframe(df6)
    # India GeoJSON
    geojson_url = "https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson"

    fig1 = px.choropleth(df6,geojson=geojson_url,featureidkey="properties.ST_NM",locations="State",
        color="Total_Amount",color_continuous_scale="Reds",title="State-wise Transaction Amount")
    fig1.update_geos(fitbounds="locations",visible=False)
    fig1.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
    st.plotly_chart(fig1)

# ---------------- INSIGHTS & FINDINGS ----------------
elif menu == "Insights & Findings":
    st.title("Insights & Findings")
    st.markdown("### 🧠 Key Business Insights")
    st.info("""
    - Digital transactions in India show strong and continuous growth over the years.
    - A few major states contribute most of the total transaction volume.
    - UPI-based payments are driving India's digital economy.
    """)
    st.markdown("---")

    st.markdown("### 📈 Transaction Insights")
    st.info("""
    - Transaction amounts are increasing year by year.
    - Peak usage is often seen in festive quarters (Q3 & Q4).
    - Merchant and peer-to-peer payments dominate usage.
    """)
    st.markdown("---")

    st.markdown("### 🧑 User Insights")
    st.info("""
    - Registered users have grown significantly over time.
    - Android devices dominate mobile usage.
    - Urban states show higher digital adoption than rural areas.
    """)
    st.markdown("---")

    st.markdown("### 🛡️ Insurance Insights")
    st.info("""
    - Insurance transactions are lower compared to payment transactions.
    - Only a few states dominate insurance usage.
    - Insurance adoption is slowly increasing over time.
    """)
    st.markdown("---")

    st.markdown("### 🌍 Geographic Insights")
    st.info("""
    - Western and Southern states lead in digital transactions.
    - Northeastern states show lower adoption rates.
    - Metro cities contribute heavily to total transactions.
    """)
    st.markdown("---")

    st.markdown("### 📊 Growth Insights")
    st.info("""
    - Strong year-on-year growth in transaction volume.
    - Both transaction count and value are increasing steadily.
    - Digital payment adoption is rapidly expanding across India.
    """)

    st.markdown("---")

    st.markdown("### 🎯 Final Conclusion")
    st.success("""
    PhonePe plays a major role in India's digital payment ecosystem.
    The platform is driving financial inclusion, but there is still scope
    for growth in rural regions and insurance adoption.
    """)

Overwriting app.py

In [54]:
!npm install localtunnel

⠙⠹⠸⠼⠴⠦⠧
up to date, audited 23 packages in 835ms
⠧
⠧3 packages are looking for funding
⠧  run `npm fund` for details
⠧
2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
⠧

In [55]:
!streamlit run app.py &>/content/logs.txt &

In [56]:
!npx localtunnel --port 8501

⠙your url is: https://nasty-toes-fall.loca.lt
^C